spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 5

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.example: INFO
    org.apache.camel: INFO
    root: INFO

server:
  port: 8080
  error:
    include-stacktrace: always

ftp:
  host: ${FTP_HOST}
  username: ${FTP_USERNAME}
  password: ${FTP_PASSWORD}
  directory: ${FTP_DIRECTORY}

camel:
  springboot:
    name: UserExportService
  dataformat:
    jackson:
      auto-discover-object-mapper: true
      date-format: yyyy-MM-dd HH:mm:ss
export:
  schedule: ${EXPORT_SCHEDULE:0 0 2 * * ?}
